CREATE OR REPLACE TRIGGER on_flight_add
  AFTER INSERT OR UPDATE ON flight
  FOR EACH ROW
BEGIN
IF :NEW.ARRDATE < :NEW.DEPDATE THEN 
      RAISE_APPLICATION_ERROR(-20001, 'Arrival date earlier than departure date');
  END IF;
  END;
/